- config/arrays/wiki/actions.yml
- config/arrays/wiki/constants.yml
- config/arrays/wiki/values.yml
- lib/tasks/generate_wiki_articles.rake
This PR adds the new Values, Constants, and Action from the 1.51 PTR update for Wiki Article generation.
> PTR 1.51 Wiki Articles

- app/views/posts/show.html.erb
- app/views/revisions/_revisions.html.erb
This PR enables links to contain scroll anchors for the comments section and the revisions section.
> Add scroll anchors to posts/show

- lib/tasks/db.rake
- Prevents regression with newer versions of Faker
- Better readability for new developers
> Remove ambiguity of positional arguments in db:fakeit task

- app/controllers/posts_controller.rb
- app/views/posts/_form.html.erb
- config/locales/en.yml
- config/locales/ko.yml
> Add dropdown to change post locale

- app/controllers/reports_controller.rb
Usually after a report is accepted, admins will want to take action on the reported content.
> Don't leave report page if report is accepted

- app/assets/javascripts/application.js
- app/assets/javascripts/disable-form-by-select.js
- app/views/reports/_form_post.html.erb
This simply enforces the stipulation in the report form that users should not submit reports under this category.
> Prevent users from submitting reports under "There's a bug in this code" category

- app/assets/stylesheets/elements/_list.scss
- app/controllers/pages_controller.rb
- app/views/application/_footer.html.erb
- app/views/application/_header.html.erb
- app/views/application/_user_block.erb
- app/views/application/banners/_ko_fi.html.erb
- app/views/pages/tos.html.erb
- app/views/sessions/new.html.erb
- app/views/users/_form.html.erb
- config/locales/en.yml
- config/locales/ko.yml
- config/routes.rb
This PR aims to explicitly enumerate the rules and policies surrounding Workshop.codes
> Add terms of service page

- app/controllers/posts_controller.rb
Previously when a user tried to create an invalid derivative, the form would not provide feedback on why it failed to submit. This PR alters the `Post#update` method to properly show the error(s) whenever an attempt to create invalid derivatives is made.
> Properly show errors when derivatives cannot be created

- app/controllers/posts_controller.rb
- app/models/notification.rb
As a poster to Workshop.codes, so that I can know that people are making remixes of my posts, I want to be notified whenever someone makes a derivative of my post.
> Notify on derivation from post

- Gemfile
- Gemfile.lock
- app/controllers/wiki/search_controller.rb
- app/models/wiki/article.rb
- build(Bundler): swap out pry for pry-byebug
- fix: Avoid erroneous "latest article" filtering
> fix wiki search

- .github/workflows/ruby.yml
- Gemfile
- Gemfile.lock
- app/controllers/forgot_passwords_controller.rb
- app/models/user.rb
- app/views/forgot_passwords/index.html.erb
- app/views/forgot_passwords/new.html.erb
- app/views/forgot_passwords_mailer/send_token.html.erb
- config/environments/test.rb
- config/initializers/new_framework_defaults_6_0.rb
- spec/support/user_helpers.rb
- spec/system/forgot_passwords_spec.rb
> password reset fix

- app/assets/stylesheets/elements/_alert.scss
- app/assets/stylesheets/utilities/_display.scss
- app/javascript/packs/application.js
- app/javascript/src/dismiss-parent.js
- app/views/admin/_navigation.html.erb
- app/views/application/_flash.html.erb
- feat: Update flash display
- fix: Prevent notifications from showing on load
- feat: Tweak some styling of the alerts
- feat: Remove outdated admin dashboard flash section
> flash rework

- .editorconfig
- .eslintrc.yml
- app/javascript/src/blocks.js
- app/javascript/src/components/Notifications.svelte
- app/javascript/src/components/form/Dropzone.svelte
- app/javascript/src/components/form/Tags.svelte
- app/javascript/src/get-partial.js
- app/javascript/src/get-post-analytics.js
- app/javascript/src/get-reports-form.js
- app/javascript/src/get-snippet.js
- app/javascript/src/get-user-analytics.js
- app/javascript/src/inscryb-mde.js
- app/javascript/src/inscrybe-mde-paste-image.js
- app/javascript/src/wiki/search.js
- chore: Update ESLint rules
- chore: Add .editorconfig
> Meta files

- app/javascript/src/dismiss-parent.js
- app/views/application/_flash.html.erb
- app/views/application/error.js.erb
- app/views/application/success.js.erb
- features/manage_posts.feature
- features/step_definitions/global_stepdefs.rb
This makes them utilize the existing flash system, standardizing the look of the website more.
> feat: Update success/error application views

- app/views/posts/_details.html.erb
- config/locales/en.yml
- config/locales/ko.yml
Addresses issue brought up at https://discord.com/channels/570672959799164958/574537911114924043/930205818425597982 (https://workshop.codes/discord)﻿
> fix(i18n): Update YAML structure to be read by post details partial

- app/views/pages/privacy_policy.html.erb
This PR fixes a few typos, inaccuracies, and omissions in the Privacy Policy.
> privacy policy update

- app/controllers/posts_controller.rb
- app/helpers/blocks_helper.rb
- app/views/blocks/post/_gallery.html.erb
- app/views/posts/_carousel_item.html.erb
> fix: Nil safety when converting `blob_id`s into Attachments

- app/assets/stylesheets/elements/_code.scss
- app/assets/stylesheets/elements/_items.scss
- app/javascript/src/infinite-scroll.js
- app/views/blocks/profile/_highlight.html.erb
This PR fixes several things related to the profile pages:
- Fix incorrect placement of the favorite button in profile highlight
- Decrease border radius in profile highlight
- Fix 404 when post no longer exists in profile highlight
- Fix infinite scroll loading even if the posts are not visible in the tab
> fix: Several profile fixes

- app/controllers/posts_controller.rb
This PR explicitly informs a user when an issue occurs with their post's derivations
> explain derivative failure

- config/locales/en.yml
- config/locales/ko.yml
> Update expiration warning

- app/controllers/posts_controller.rb
- app/views/blocks/profile/_cards.html.erb
- app/views/blocks/profile/_carousel_cards.html.erb
- app/views/blocks/profile/_highlight.html.erb
- app/views/posts/_posts.html.erb
- app/views/profiles/show.html.erb
- spec/features/profiles_spec.rb
- spec/rails_helper.rb
- spec/requests/profiles_spec.rb
> fix: Ensure pagination works within profiles

- app/views/admin/reports/_comment.html.erb
- app/views/admin/reports/show.html.erb
- spec/factories/comments.rb
- spec/features/admin_reports_spec.rb
- spec/rails_helper.rb
- spec/system/forgot_passwords_spec.rb
This PR adds a few nil safety and existence checks in the reports show page in order to fix #166.
> fix: Error handling on report show

- app/controllers/filter_controller.rb
- app/controllers/search_controller.rb
- app/javascript/src/components/form/Derivatives.svelte
- features/step_definitions/derivative_stepdefs.rb
- features/support/debugging.rb
> fix: Code search in derivatives form

- Gemfile
- Gemfile.lock
- app/models/post.rb
- app/models/user.rb
- app/views/posts/_post_recommendations.erb
- app/views/posts/_recommended_posts.erb
- app/views/posts/_user_recommendations.erb
- app/views/posts/index.html.erb
- app/views/posts/show.html.erb
- db/migrate/20220818142511_create_disco_recommendations.rb
- db/schema.rb
- lib/tasks/update_recommendations.rake
This PR uses the awesome https://github.com/ankane/disco gem to add recommendations.
There are two types of recommendations;
1. User recommendations. These are general recommendations for posts based on your favorites and the favorites of other users. These show on the homepage for users who have favorites and recommendations based on those favorites.
2. Post to post recommendations. These are recommendations for a single post based on users who have favorited this and other posts. These show on post show pages only if the post has any favorites and has recommendations. **It might turn out that this creates too many db records, I'm really not sure. If this is the case I might end up removing these recommendations.**
Both of these recommendations are only based on what favorites they have …
> feat: User based and post to post recommendations

- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/components/editor/FindReplaceAll.svelte
Demonstration of PR in action:
> feat: Auto-fill search input when pressing Ctrl + Shift + F

- app/javascript/src/lib/OWLanguageLinter.js
Removes the "Missing Semicolon" error from block comments and lines that end with empty characters
> "Missing Semicolon" fixes

- app/assets/stylesheets/utilities/_flex.scss
- app/views/profiles/_form.html.erb
- app/views/profiles/edit.html.erb
I actually spent 15 minutes looking for it... with the code for it next to me 🫠 
Wording could be better here. I'll leave that open to suggestions from you.
> Direct verified users to their profile page to edit custom css

- app/assets/stylesheets/elements/_codemirror.scss
- app/controllers/editor_controller.rb
- app/javascript/src/components/editor/Editor.svelte
- app/views/editor/index.html.erb
- config/arrays/wiki/actions.yml
- config/arrays/wiki/constants.yml
- config/arrays/wiki/defaults.yml
- Added missing colors and events.
- Fixed a bug where Color would autofill Color(Color(White)).
- Changed default number to 0 (making for example vector default Vector(0, 0, 0) rather than Vector(1, 1, 1). for loops also begin at index 0, rather than 1).
> adding missing colors and events

- app/views/application/_header.html.erb
- config/locales/en.yml
- config/locales/ko.yml
- config/routes.rb
> Add link to text editor in header

- .vscode/settings.json
This PR adds eslint validation for .svelte files for vs code
> chore: Add .vscode/settings.json

- app/javascript/src/utils/compiler.js
By itself this doesn't change anything, but it makes it very easy to expand what conditions can hold in the future
> Editor: Parse conditional conditions manually

- app/javascript/src/lib/OWLanguageLinter.js
Not sure when or if we will ever implement `@else if`, but this should prevent some confusion.
> Editor: Add lint rule for @else if uses

- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/components/editor/ProjectsDropdown.svelte
- app/javascript/src/utils/project.js
- Fix crash creating demo project in the first place
- Fix Save and Import buttons showing for non signed-in users
- Hide Edit dropdown for non signed-in users, as they cannot use any of the buttons in there
> Editor: Fix some issues with the demo project when not signed-in

- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/elements/_carousel.scss
- app/assets/stylesheets/elements/_codemirror.scss
- app/assets/stylesheets/elements/_items.scss
- app/assets/stylesheets/general/_general.scss
- app/helpers/posts_helper.rb
- app/javascript/src/carousel.js
- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/components/editor/Settings.svelte
- app/views/posts/_carousel.html.erb
- app/views/posts/_current_user_blocks.html.erb
- app/views/posts/_expired.html.erb
- app/views/posts/_overwatch_2_indicator.html.erb
- app/views/posts/_tabs.html.erb
- app/views/posts/show.html.erb
- package.json
- yarn.lock
This PR adjusts the design of show pages in fairly subtle ways. Each section is divided in blocks, with the intend to make it a little more well organized, a little more open, and it looks nice.
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/12848235/233215181-fde70785-f126-4b05-9c9b-fedc2570d3f6.png) | ![image](https://user-images.githubusercontent.com/12848235/233215093-f6af112b-cdd9-47a9-be73-41bc710906fc.png) |
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/12848235/233215356-46225e65-ab7b-488d-8806-5955cafc6d7f.png) | ![image](https://user-images.githubusercontent.com/12848235/233215342-80317899-5f5a-4fde-8dbc-466d8507e5d9.png) |
| Before | After |
| --- | --- |
| …
> style: Post show design changes

- app/controllers/wiki/search_controller.rb
- app/javascript/src/components/editor/EditorWiki.svelte
- Render header anchors on the server side
- Manually handle jumping to headings
> Make links to headings/sections of an wiki article work in the Editor wiki sidebar

- app/javascript/src/components/editor/Shortcuts.svelte
Also fix keybind for Search/replace
> Add Redo keybind to editor shotcuts list

- app/javascript/src/components/editor/ScriptImporter.svelte
Small QoL improvement suggested in Discord
> Clear input when script importer is open

- app/javascript/src/lib/OWLanguageLinter.js
Checks for `event {}` blocks with an event that requires arguments (e.g. Subroutine, Ongoing - Each Player), and warns the user if some arguments are missing.
In the future, we may want to get the list of arguments from `config/arrays/wiki/events.yml`.
> Add Editor linter to check for event types with missing arguments

- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/lib/OWLanguageLinter.js
- app/javascript/src/stores/editor.js
> Add Editor linter to check for usages of subroutines that aren't defined anywhere on the project

- app/assets/stylesheets/editor/_project-backups.scss
- app/assets/stylesheets/elements/_buttons.scss
- app/controllers/project_backups_controller.rb
- app/controllers/projects_backups_controller.rb
- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/components/editor/Empty.svelte
- app/javascript/src/components/editor/Modals/BackupsModal.svelte
- app/javascript/src/components/editor/Modals/CreateProjectModal.svelte
- app/javascript/src/components/editor/Modals/Modal.svelte
- app/javascript/src/components/editor/ProjectsDropdown.svelte
- app/javascript/src/components/editor/Save.svelte
- app/javascript/src/inscryb-mde.js
- app/javascript/src/stores/editor.js
- app/javascript/src/utils/project.js
- app/javascript/src/utils/projectBackups.js
- app/models/project.rb
- app/models/project_backup.rb
- config/routes.rb
- db/migrate/20230812221036_create_project_backups.rb
- db/schema.rb
- spec/factories/project_backups.rb
- spec/models/project_backup_spec.rb
This PR adds backups for editor projects. There is a new option under the "save" button, allowing you to create a backup. What this does is create a copy of your current project. It's not a direct copy, it's under a new model. Only the content and title gets copied. A project can have an unlimited amount of backups. You can load a backup and it will replace the current content with the backup. The project will not actually be replaced until you save, but ctrl+z'ing is impossible after replacing from the backup. The only way to restore is by refreshing. Ideally of course if you've pressed the restore from backup button, you meant to do it and there's no need to go back. We can rework that if that proves incorrect.
Additionally this PR refactors modals in some fashion. There now is a …
> feat: Editor project backups

- app/javascript/src/components/actions/escapeable.js
- app/javascript/src/components/actions/outsideClick.js
- app/javascript/src/components/actions/submittable.js
- app/javascript/src/components/editor/EditorActions.svelte
- app/javascript/src/components/editor/EditorItemCreate.svelte
- app/javascript/src/components/editor/ProjectsDropdown.svelte
- app/javascript/src/components/editor/Save.svelte
- app/javascript/src/components/editor/Settings.svelte
- app/javascript/src/components/editor/Shortcuts.svelte
This is another pattern we can extract away into an Svelte action.
Though since it is pretty much only used for dropdowns, maybe we should just have a dropdown component.
More details in the commit messages.
> Add `outsideClick` Svelte action

- app/controllers/archives_controller.rb
- spec/requests/archive_spec.rb
> prevent error when archive controller is provided a post code that doesn't exist

- app/javascript/src/components/editor/Modals/ScriptImporterModal.svelte
Use `RegExp.exec()` and `getClosingBracket()`. Now we create items for each rule, from where the rule starts being defined ("rule(...) {...") to the closing bracket.
While the old implementation was more lenient on what it included, this way we can fix a bug where the "disabled" tags on rules were being skipped over when importing.
> Reimplement `findAllRules()` in Editor script importer

- app/javascript/src/utils/compiler/for.js
- spec/javascript/utils/compiler/for.test.js
```
@for (i from 0.5 to 2.1) { For.i; }
@for (j from 0.5 through 2.1) { For.j; }
```
Results in
```
0.5; 1.5;
0.5; 1.5; 2.5;
```
```
@for (-1 to 1 in steps of 2) { For.i; }
```
Results in
```
-1; 1;
```
Which is very useful for things like creating symmetrical effects.
> Allow usage of negative and decimal numbers in @for loops in the Editor

- config/arrays/wiki/defaults.yml
- `Count Of` → `Count Of(Array())` (added parenthesis)
- `String` → `Custom String("")` (removed "Some string" text)
This should work nicely alongside #419 :)
> Update default values for parameters to match the default values from the in-game editor

- package-lock.json
- package.json
Reverts Mitcheljager/workshop.codes#467
Going from v2 to v3 broke a bunch of things
> Revert "chore(deps): bump d3-color and metrics-graphics"

- .husky/pre-commit
- app/javascript/scss/editor/_editor.scss
- app/javascript/src/components/editor/EditorAside.svelte
- package.json
Fixes #479
- **fix(husky): update to v9**
- **fix(lint-staged): include .ts and .svelte files in commit linting**
- **feat(editor): make "Add Item" button in aside sticky to bottom**
> feat(editor): make "Add Item" button in left sidebar sticky to bottom

- app/javascript/scss/editor/_editor.scss
- app/javascript/src/components/editor/EditorAside.svelte
This PR addresses the review comments on #480
- **style: make class name more BEM-compliant**
- **fix(editor): prevent folder arrow indicator from appearing above Add Item button**
> fix: pr comments on #480

- app/views/wiki/_quick_navigation.html.erb
- config/arrays/wiki/actions.yml
- config/arrays/wiki/constants.yml
- config/arrays/wiki/defaults.yml
- config/arrays/wiki/values.yml
- lib/tasks/generate_wiki_articles.rake
- lib/tasks/upgrade_wiki_articles.rake
This PR adds a rake task to upgrade wiki articles. This rake task is as ugly as it gets, but as it's a one time thing, I don't care. Verboseness over cleverness, and temporary cleverness over maintainability here.
Articles are changed to a new format;
- Description
- Snippet
- Properties
- Return value
- Parameters
- Parameter details
Each article will now have a tiny snippet, this is super basic and only shows the value/action with it's default values. In some cases it doesn't make sense to use these in their isolated context, but it helps with copy pasting.
Previously the articles had a separate "return" section, but this is now under the "properties" section. This section lists both the return value and the parameters. The parameters are shown with a large details block, similar to …
> feat: Upgrade value/action wiki articles with rake task

- app/javascript/src/components/form/Snippet.svelte
The Snippet component is used in post forms to autofill settings based on your snippet. This component held a lot of confusing logic or outdated, so rather than just converted it to Svelte 5 and TS I also opted to refactor a ton of logic.
- The converter for Mccree -> Cassidy is out, it's been long enough.
- Several variables that held global state are out, and several functions that were quite interconnected are now... less interconnected.
It's still not the prettiest component of all time, but at least it's much easier to follow.
> refactor(svelte5): Use TS and Svelte 5 syntax for Snippet component

- app/javascript/src/components/Ollie.svelte
- app/javascript/src/types/global.d.ts
This PR refactors the Ollie component to use TS and Svelte 5. This component is used to show a fun animation when favoriting a post. I had to add `onfavorite` as a custom event on the global namespace in order for the event to be recognized.
> refactor(svelte5): Use ts and Svelte 5 syntax for Ollie component.

- app/javascript/src/components/Bugsnag.svelte
Not much going on in this one!
> refactor(svelte5): Use ts and Svelte 5 syntax for Bugsnag
