- Gemfile
This PR ensures that local development of the project can occur on non-Windows platforms
> Avoid installing win32-security gem on non-Windows platforms

- app/assets/javascripts/application.js
- app/assets/javascripts/reveal-on-difference.js
- app/views/posts/_form.html.erb
- config/locales/en.yml
- config/locales/ko.yml
It is often the case that newer Workshoppers will not realize that they are able to upload updates to their gamemodes to the existing associated import code. This warning will help educate those people.
> Add warning about changing import code on revisions

- app/helpers/reports_helper.rb
- app/views/reports/_form.html.erb
- config/locales/en.yml
Add new options to report form:
`There's a bug in this code` and `I can't import this code`
Selecting them reveals additional warnings when reports should not be submitted.
This should reduce the amount of `Other` reports reporting a bug in a code.
> Improve text and warnings on report form

- app/helpers/reports_helper.rb
- app/views/reports/_form_post.html.erb
Users would frequently mistake the intent of "This code does not work" to mean that the post did not function as intended, when the true intention was more in line with the "I can't import this code" category.
> Remove "This code does not work" report category

- app/assets/stylesheets/elements/_buttons.scss
Currently, it is sometimes difficult to tell if a button is disabled or not, because it will appear to have a similar color to its normal appearance. This change prevents that issue by applying a gray background color to the button when it is disabled.﻿
_Example of disabled button (live)_
_New disabled button_
> Make disabled buttons actually look disabled by greying them out

- .github/workflows/ruby.yml
This pull request changes two things about the current GH Actions flow:
- Linters are now run in parallel to specs
- Specs and linters will now run to completion regardless of fails/errors
The first change was made to facilitate faster CI runs. The second change was made to allow developers to see all the currently failing CI tests in a single run.﻿
> GitHub Actions tweaks

- app/controllers/application_controller.rb
- app/helpers/posts_helper.rb
- app/serializers/post_serializer.rb
- app/views/application/_body_bg.html.erb
- app/views/blocks/post/_gallery.html.erb
- app/views/filter/get_verified_users.html.erb
- app/views/posts/_carousel.html.erb
- app/views/posts/_carousel_item.html.erb
- app/views/posts/form/_image_upload.html.erb
- app/views/posts/show.html.erb
- app/views/profiles/_form.html.erb
- app/views/profiles/_image.html.erb
- config/routes.rb
This enables developers to test image-related features without needing to possess a CDN. Developers may still choose to use a CDN in development by editing `config/storage.yml`
> Ask Rails to acquire the image URL instead of requiring CDN

- app/assets/stylesheets/elements/_carousel.scss
- app/javascript/packs/application.js
- app/javascript/src/turbolinks-prefetch.js
- app/views/application/_locale_picker.html.erb
- app/views/application/_user_block.erb
- app/views/filter/_filter.html.erb
- app/views/sessions/new.html.erb
When hovering a link the page is prefetched and placed in to Turbolinks cache. The result is that the page starts loading before the user actually clicks, potentially shaving off all perceived load times. The downside is that you're potentially making requests that are never actually visited. All links are prefetched by default, but some links are excluded because either they are too heavy and I don't want to preload them just incase they never get used (e.g. analytics pages), or they don't make sense to prefetch (e.g. log out).
Most of this PR is an edit from an https://github.com/huacnlee/turbolinks-prefetch, which I had to adjust to make more sense for our use case.
> Prefetch links on hover to decrease perceived load times

- app/models/post.rb
- config/webpack/loaders/svelte.js
- db/migrate/20210908174125_change_post_controls_default.rb
- db/schema.rb
This pull request accomplishes two minor goals:
- Enable loading of Svelte in dev mode within development environments. This change can be used in tandem with a tool such as [Svelte DevTools](https://github.com/RedHatter/svelte-devtools) to enable easier Svelte component debugging.
- Solves #71 by ensuring that undefined controls are re-saved as blank. However, if filled controls are somehow saved as `undefined`, a new issue should be opened.
> Fix controls + enable Svelte debugging

- app/controllers/posts_controller.rb
- Previously, attempting to create invalid derivatives while creating a post would not show errors, but updating a post would.
- Previously, attempting to update a post with no derivatives would result in a client-side error despite the update happening correctly.
> Fix a few bugs with derivative error feedback

- .gitignore
The ignored file is solely to support the --only-failures
flag in RSpec, and is not meaningful to include in the repository.
> chore: Update .gitignore to ignore RSpec results

- Gemfile
- Gemfile.lock
- app/views/sessions/new.html.erb
- config/routes.rb
- spec/requests/csrf_requests_spec.rb
Mitigates [CVE-2015-9284](https://nvd.nist.gov/vuln/detail/CVE-2015-9284). More information can be found in [this discussion](https://github.com/omniauth/omniauth/pull/809).
﻿- test: Ensure CSRF cannot occur
- fix: Prevent CSRF attacks
- fix: Undo unnecessary restriction to callback
> csrf protection

- config/initializers/bugsnag.rb
Previously, Bugsnag could not fully utilize the
new GitHub integration because releases were not
properly tagged. This change enables Bugsnag
to track release versions.﻿
> chore: Tag Heroku release versions

- config/initializers/new_framework_defaults_6_1.rb
This is due to the migration of web browsers towards dropping cookies which specify SameSite: None and do not specify the Secure attribute (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite)
> chore: Enable SameSite: Lax on cookies

- babel.config.js
Prevents this set of messages from appearing during the `assets:precompile` phase
```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
```
> fix(webpack): "loose" config warnings

- app/views/pages/privacy_policy.html.erb
- app/views/pages/tos.html.erb
Some aspects of the Privacy Policy were outdated or misleading, which has been addressed (namely, the deprecation of the Cloudflare cookie). A policy clarification is also included to ensure that users are aware that import codes which function essentially identically to a provided preset are not permitted.
CHANGELOG:
- feat: Remove information about __cfduid
- feat: Update information about third parties in Privacy Policy
- feat: Make Privacy Policy slightly easier to read
- feat: Include Last Updated date on privacy policy
- feat: Add last updated date to ToS
- feat: Add 'substantive' stipulation to terms of service
> feat: Update Terms of Service and Privacy Policy

- app/assets/stylesheets/elements/_standout.scss
- app/assets/stylesheets/elements/_tabs.scss
- app/assets/stylesheets/general/_form.scss
- app/views/application/banners/_ko_fi.html.erb
- app/views/posts/form/_form.html.erb
- app/views/profiles/show.html.erb
The element would get blocked by some adblockers because `.banner` is identified as an ad. This fixes that by renaming the class to `.standout` (naming is hard ok)
> fix: Rename banner class to standout to fix adblocker blocking the element

- .github/workflows/ruby.yml
The environment was practically useless anyways, since it did not contain any environment variables the workflow did not override or not use altogether.
> ci: Remove environment for some CI tasks

- app/controllers/sessions_controller.rb
- app/models/user.rb
- features/linking_accounts.feature
- features/step_definitions/authentication_stepdefs.rb
- features/step_definitions/user_stepdefs.rb
This pull request fixes an issue where verified users who logged in via Battle.net could not link their similarly-named Discord accounts.
I also took the opportunity to flesh out the test suite for linked accounts.
> fix: Allow linking similar-username accounts to verified Battle.net accounts

- app/controllers/filter_controller.rb
- app/controllers/posts_controller.rb
- app/models/post.rb
This prevents refreshes from triggering unnecessary re-requests to
the Elasticsearch cluster, and eases load in general, as the suggested
modes do not need to be immediately updated.
Fixes #90
> perf: Cache `similar_to` post search

- app/assets/stylesheets/elements/_alert.scss
- app/controllers/favorites_controller.rb
- app/views/application/error.js.erb
- app/views/application/success.js.erb
Sometimes when favoriting or removing a favorite the post can not be found. I'm not sure why this happens, but it does. This now brings up an alert showing that something went wrong.
I've also slightly tweaked the styling of the close button of the alert, making it a little smaller.
> fix: Handle errors when favoriting

- app/javascript/src/get-partial.js
- app/javascript/src/remove-and-add-event-listener.js
- app/views/comments/_form.html.erb
- app/views/posts/_similar_to.html.erb
This PR makes it so the Similar Codes on post/show only load if they are actually scrolled to. This is to prevent unnecessary calls to ElasticSearch for something that may never get seen.
You can now pass `data-lazy="true"` to an element with `data-action="get-partial"` to lazy load it on scroll. This same function can be used to either load immediately on page load or load on click. It's currently only used for these similar codes, so the other functions are a little redundant, but might as well keep them for some other time.
> feat: Lazy load similar codes when scrolled to

- app/views/filter/index.html.erb
- app/views/posts/form/tabs/_settings.html.erb
The OW2 Beta currently has import codes, but no Workshop. This PR updates the site to reflect that.
Commits:
- Revert "fix: Disable OW2 for now and display a message on the filter page"
- feat: Add explanation of OW2 Beta lobbies
> Update OW2 Beta information/features

- app/controllers/filter_controller.rb
- app/javascript/src/infinite-scroll.js
- app/views/filter/index.html.erb
- app/views/posts/_posts.html.erb
- app/views/posts/infinite_scroll_posts.js.erb
- spec/system/forgot_passwords_spec.rb
Previously, if Elasticsearch returned an error during search, it would fail silently. This PR explains the issue to the user and offers a retry option.
This button appears whenever Load More or Infinite Scroll fails to load more posts via Ajax:
Pagination users will be given an error page:
> feat: Add graceful UX for search page errors

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/models/user.rb
- db/migrate/20220509180005_enable_uuid.rb
- db/migrate/20220509180158_add_uuid_to_models.rb
- db/schema.rb
This PR adds a UUID to the User model which is used to ensure that a session cannot incorrectly log a user into an account they do not own, which fixes #140. For user convenience, legacy sessions will continue to function.
This PR also includes a countermeasure to prevent [session fixation attacks](https://edgeguides.rubyonrails.org/security.html#session-fixation).
> User session cookie improvements

- app/assets/stylesheets/elements/_feed.scss
- app/assets/stylesheets/elements/_profile.scss
- app/controllers/feed_controller.rb
- app/helpers/application_helper.rb
- app/views/application/_user_block.erb
- app/views/feed/_feed_item.html.erb
- app/views/feed/_feed_items.html.erb
- app/views/feed/index.html.erb
- app/views/feed/infinite_scroll_feed_items.js.erb
- app/views/layouts/_account.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20220508135642_add_feed_last_visisted_at_to_users.rb
- db/schema.rb
This PR adds a feed to the account pages that shows updates to modes you have favorited. This is the first step to added a more interactive feed, in the future I hope to add more things such as comments placed, recommendations based on your favorites, users you might be interested in, etc.
When you visit the feed a field is updated on the user model that tracks when you last visited the feed. This was in favor of a cookie since that wouldn't work across different browsers/devices.
With this also comes a bit of a redesign for the menu on the account pages on mobile. Before the menu took up the entire screen and it was hard to navigate as a result. I've replaced it with a select field that navigates on change. For this I refactored the user user items in to a single object, making it a bit …
> feat: Favorites feed

- app/assets/stylesheets/elements/_card.scss
- app/assets/stylesheets/utilities/_display.scss
- app/views/posts/_analytics.html.erb
This PR adds the total impressions count to post analytics. It also adds cards similar to the analytics on the user overview page. I also wanted to add total copies count but we don't have a cache counter for that yet so I will leave that for a separate PR.
| Desktop | Mobile |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/12848235/171997851-25d8685a-73cd-4f28-b0d9-5de7049e2e82.png) |  ![image](https://user-images.githubusercontent.com/12848235/171997887-137c3a01-7a0a-416d-93d1-5fb69f93dc41.png) |
> feat: Update post analytics with impressions count

- app/controllers/comments_controller.rb
- app/javascript/src/get-partial.js
- app/views/posts/_tabs.html.erb
This PR adds a scroll anchor to comment notifications so it scrolls to the correct comment on load. Since the comments are loaded async this required adjusting the `getPartial` function to scroll after loading. The added benefit of this is that the scroll is smooth rather than instant, which looks neat. I've also refactored parts of this function to catch errors and show them, just in case.
> feat: Scroll anchor for comment notifications

- app/assets/stylesheets/logged_in_user/_inscryb-mde.scss
The editor was incorrectly applying some of it's own styling. With this PR that styling is overwritten.
> style: Fix incorrect styling of tables in editor

- app/views/posts/index.html.erb
This PR makes it so we can set the OW2 banner on the homepage conditionally with an env variable. I decided to go with a general variable for the banner so we could potentially use it for other banners later down the line.
> feat: Show OW2 banner only if env var is set

- app/javascript/packs/application.js
- app/javascript/src/analytics.js
- app/javascript/src/copy.js
- app/models/post.rb
- app/views/application/_analytics_code.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/privacy_policy.html.erb
This PR removes Google Analytics and all of it's components. At the moment we don't use it much and we're better off with the increased speed, better user experience, and without selling out our users.
> chore: Remove Google Analytics

- app/assets/stylesheets/logged_in_user/_images-preview.scss
- app/controllers/application_controller.rb
- app/javascript/src/components/form/Dropzone.svelte
- app/views/posts/form/_image_upload.html.erb
This PR adds the option to click on images in the dropzone to display them fullscreen, like you would in the carousel if you click "view original size". The modal is a bit of a mash between svelte and regular js. I would like to refactor the modal to be fully Svelte at some point, but that's for another PR.
> feat: Add image previews to dropzone

- app/controllers/filter_controller.rb
- app/controllers/search_controller.rb
- app/javascript/src/filter.js
- app/javascript/src/infinite-scroll.js
- config/routes.rb
- spec/requests/search_urls_spec.rb
As detailed in #165, query parameters are easier to work with for applications integrating with Workshop.codes, and may be better understood by SEO algorithms.
Resolves #165
> refactor: use query parameters instead of path-based parameters

- app/assets/stylesheets/_mixins.scss
- app/assets/stylesheets/elements/_header.scss
- app/assets/stylesheets/elements/_logo.scss
- app/assets/stylesheets/elements/_navigation.scss
- app/assets/stylesheets/elements/_noui-slider.scss
- app/assets/stylesheets/general/_form.scss
- app/assets/stylesheets/logged_in_user/_switch.scss
- app/javascript/src/components/form/Dropzone.svelte
This PR improves the `focus` and `focus-visible` states for several elements, mainly form elements. `focus-visible` is only visible when using keyboard navigation. This focus should always be clearly visible and the way it looks is far less important than the functionality.
The regular focus state for form elements was previously non existent. I've added a slight highlight and outline to inputs.
> feat: Improve focus states for several form elements

- app/models/email_notification.rb
- app/models/user.rb
Due to [this change in Lockbox](https://github.com/ankane/lockbox/commit/7477de8bfba5c7f0bf3d77c1cafd85e9411ae92b), it is necessary to rename `encrypts` to `has_encrypted`.
> chore: Avoid deprecation warning for encrypted email

- app/controllers/search_controller.rb
This PR fixes some scenarios in which a search engine might construct a request such as
```
POST /search?search=doomfist+parkour
```
This previously caused an error due to the POST request handler expecting a `query` parameter and not a `search` parameter.
Fixes #175.
> fix: Fix some errors with search controller code

- app/controllers/filter_controller.rb
- app/controllers/search_controller.rb
- app/javascript/src/filter.js
- spec/requests/search_urls_spec.rb
Due to changes made in #171, the previous `filter.js` improperly named its query parameters, meaning the filters did not function. This PR rectifies that.
Examples:
`categories=___` -> `category=___`
`maps=___` -> `map=___`
> fix: Search filters not properly applying

- public/robots.txt
This PR updates robots.txt to disallowed Yandex and PetalBot. PetalBot is a chinese bot from Huawei. We have no interest in chinese traffic as our codes won't work anyway. Yandex is Russian, and while a somewhat significant portion of traffic comes from Russia, I see no point in allowing them to index us.
I've also added a crawl-delay (I thought we had this already, but I guess not). This will prevent future bots from crawling too aggressively, as long as they respect it of course.
> chore: Update robots.txt with Yandex and PetalBot

- app/javascript/src/filter.js
- spec/features/search_and_filter_spec.rb
This PR fixes an issue where the search box would not properly encode queries if JavaScript was enabled.
Fixes #180
> fix: Incorrect encoding in search box

- app/controllers/comments_controller.rb
- app/views/comments/_form.html.erb
- spec/features/comment_spec.rb
This PR fixes a few minor issues with comment handling. In particular:
- The comments controller did not properly respond with an error due to a lack of an enclosing `respond_to` block
- The comments form did not contain a `required` attribute, which led to poor user feedback.
This PR also contains regression tests to capture the current behavior
> fix: Prevent undefined behavior with blank comments

- spec/features/profiles_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/requests/profiles_spec.rb
Due to a rare test ordering bug, it was possible, though unlikely, for testing of the `application_helper`'s i18n values to cause a test interdependency with the profiles specs. This PR addresses this concern.
Note: Issue was first noticed with `bundle exec rspec --seed 17258` in [this CI run](https://github.com/CactusPuppy/workshop.codes/runs/7799224654?check_suite_focus=true)
> test: Prevent rare test interdependency

- app/controllers/application_controller.rb
This PR fixes a potential bug resulting from a truthy but blank value (such as `{}`) being the returned value of `session[:user_uuid]` causing a full session reset.
> fix: Prevent truthy but blank values from causing an unneccesary session reset

- app/assets/stylesheets/elements/_backgrounds.scss
- app/assets/stylesheets/elements/_buttons.scss
- app/assets/stylesheets/elements/_card.scss
- app/assets/stylesheets/elements/_code.scss
- app/assets/stylesheets/elements/_dropdown.scss
- app/assets/stylesheets/elements/_filter.scss
- app/assets/stylesheets/elements/_footer.scss
- app/assets/stylesheets/elements/_items.scss
- app/assets/stylesheets/elements/_profile.scss
- app/assets/stylesheets/elements/_search.scss
- app/assets/stylesheets/elements/_standout.scss
- app/assets/stylesheets/elements/_user-block.scss
- app/assets/stylesheets/elements/_well.scss
- app/assets/stylesheets/general/_form.scss
- app/assets/stylesheets/general/_general.scss
- app/assets/stylesheets/logged_in_user/_chart.scss
- app/assets/stylesheets/wiki/_search.scss
- app/controllers/accessibility_controller.rb
- app/helpers/users_helper.rb
- app/views/accessibility/edit.html.erb
- app/views/admin/users/index.html.erb
- app/views/posts/index.html.erb
- db/migrate/20220818092440_remove_simple_view_from_users.rb
- db/schema.rb
The simple view is super broken and the site is unusable with it turned on. Maintaining it is not worth the effort as hardly anyone ever used it and it's purpose isn't clear. What it is trying to do should instead be done via other ways as having to toggle it isn't a good experience.
> chore: Remove simple-view accessibility setting

- lib/tasks/notify_expiry.rake
The previous expiry notification copy was inaccurate due to updates in the Overwatch custom game code expiration system. This PR updates the copy to reflect that.
> feat: Make expiry notification copy more accurate

- app/controllers/application_controller.rb
The controller action `set_current_user` was originally introduced in commit 05369c1a1a29b3d2f71c4a486017eeb577ad2e84 to perform a `nice_url` check, but has since been replaced with a differing check against the record itself in e40c55e77221142ab26ba7414749f4cf8c5697a7.
Thus, this action is no longer necessary and only contributes to clogging up stacktraces in our automated tooling.
> refactor: Remove `set_current_user`

- app/controllers/wiki/dictionary_controller.rb
- app/views/wiki/dictionary/_item.html.erb
- app/views/wiki/dictionary/index.html.erb
This PR adds a quick and dirty HTML endpoint to the already existing `/wiki/dictionary` json endpoint. The code isn't the nicest ever, but it's meant to be fairly rudimentary and so I'd rather not spend too much time on it.
Each item is generated from the actions and values .yaml files. Their links _should_ always match up, even though they aren't directly compared. Old article urls still redirect to new ones in case any article was renamed.
> feat: Add html endpoint to wiki dictionary

- app/controllers/filter_controller.rb
- spec/requests/search_urls_spec.rb
This PR fixes the format of a request (e.g. "application/json") not being preserved when redirecting from legacy search paths
> fix: Legacy JSON redirect

- app/controllers/posts_controller.rb
- app/views/application/_header.html.erb
- app/views/posts/index.html.erb
- app/views/posts/latest.html.erb
- config/routes.rb
With the refactor of URLs pagination broke on the homepage. The homepage was always a bit messy in that it was not _just_ the homepage, it was also the latest page in disguise. With this PR latest is moved to it's own action with it's own url `/latest`. A redirect is added for SEO, as `/page/1` is a very popular page.
> refactor: Move latest posts to their own action

- app/javascript/src/utils/compiler.js
This PR fixes a missing import in the compiler for the Workshop.codes editor.
> fix: Add missing compiler import

- app/javascript/src/components/editor/ProjectsDropdown.svelte
- app/javascript/src/lib/alerts.js
This PR adds an item to the Edit menu which allows the user to rename their project.
When the user renames their project, they will be shown a notification which informs them that the operation was successful:
> feat: Add ability to rename projects

- app/javascript/src/components/editor/Editor.svelte
This PR fixes a minor issue where renaming a project would not update the document title
> fix: Update document title when project is renamed

- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/components/editor/ProjectsDropdown.svelte
With #210 adding another source of truth for the document title which the `svelte:head` component formerly provided, this PR eliminates the latter. The `svelte:head` component, for reasons not entirely known, does not respond to the updating of the `$currentProject` object, either by alteration of its properties or by reassignment, but the reactive statement does.
> refactor: Ensure only one source of truth for document title

- .github/workflows/ruby.yml
- Gemfile.lock
- features/support/debugging.rb
- features/support/setup.rb
With Firefox becoming a Snap package in Ubuntu 22.04, Firefox can no longer read the `/tmp` directory where Geckodriver puts temporary profile files (see [the "Fixed" section of these release notes](https://github.com/mozilla/geckodriver/releases/tag/v0.32.0)). To work around this, we must now set `TMPDIR` to a directory under the `$HOME` of the current user, and create that directory as well.
> ci(Cucumber): Fix Cucumber Feature Check

- app/javascript/packs/application.js
- app/javascript/src/infinite-scroll.js
- app/javascript/src/timeago.js
- app/views/posts/_post.html.erb
- config/locales/en.yml
- config/locales/ko.yml
This PR replaces the expiry message (pictured below),
with a field showing the last revision date of the post (pictured below)
KNOWN ISSUES:
- The current timeago render does not consider the user's current locale
This PR resolves #224.
> feat: Replace expiry message with last updated date

- .github/workflows/ruby.yml
- features/support/setup.rb
This PR undoes the changes made in #227.
As it turns out, GitHub Actions runners actually come with a non-Snap Firefox installation, which is perfectly capable of reading the `/tmp` directory. All we need to do is avoid updating Firefox to the Snap version.
> ci(Cucumber): Use pre-installed non-Snap firefox

- app/javascript/src/zez-ui/workshop.js
This PR adjusts some things in the Zez ui to try and better the performance.
In a nutshell:
- Replace `key in object` with `object[key] !== undefined`
- Replace `for key in object` loops with regular for loops
- Reduce loops that loop over loops
> chore: Zez UI optimizations

- app/assets/stylesheets/elements/_standout.scss
- app/views/application/banners/_editor.html.erb
This PR fixes an issue where certain parts of the site which use the `standout` CSS class had unintentional/unintuitive styling applied. The issue arose due to styling initially added to highlight Workshop alternatives on the front page targeting generic elements instead of elements with certain classes. This PR changes the styling for the front page to use specific classes.
Example of broken styling:
Inspector showing the specificity override from frontpage styling:
Fixed styling:
Inspector showing lack of styling pollution:
> refactor/fix: Prevent unintended styling under `.standout` elements

- app/assets/stylesheets/elements/_bubble.scss
- app/assets/stylesheets/elements/_show-on-focus-within.scss
- app/views/posts/form/_form.html.erb
- app/views/posts/validation.js.erb
To reduce the amount of posts from confused users who aren't exactly sure what to do we show a popup when focusing the code input. This popup provides two options, one links to the wiki article on how to generate a code, the second option links to the workshop.codes editor.
The popup is shown entirely with css and is shown while focusing the input. It being just css is not really relevant, but it makes it easy to use.
The popup is only shown to users who have not yet created any posts. With this we assume that those who have created posts (that are not destroyed by us) know what they are doing.
This PR also includes a fix for validation errors caused by the number of players slider, preventing it from properly showing the error status in the tabs.
> feat: Show info bubble in code input for users who have not created any posts

- app/assets/stylesheets/editor/_matches.scss
- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/components/editor/EditorAside.svelte
- app/javascript/src/components/editor/FindReplaceAll.svelte
- app/javascript/src/components/editor/ItemFinder.svelte
- app/javascript/src/components/editor/ProjectsDropdown.svelte
- app/javascript/src/utils/editor.js
This PR adds Search/replace all to the Editor. This works by searching the content of all items and saving the found items index to an array. These indexes are only used to highlight the occurrences shown in the UI. When actually replacing the values we loop over all items that have occurrences and `.replaceAll` the value with the replacement.
Found items can be opened by clicking them or by using arrow key up and down and pressing enter while focusing either the search or the replace inputs. Pressing enter does not automatically submit the replace form, both to allow for opening of items with enter and to prevent accidentally submitting.
The inputs are hidden by default but can be opened with ctrl+shift+f, at which point you're automatically focused on the search input.
> feat: Search/replace all in w.c editor

- config/arrays/wiki/constants.yml
The constants file contained filler icon descriptions which impacted both wiki article generation and the new Workshop editor autocomplete suggestions. This PR removes them as they are unnecessary.
> fix: Prevent `__iconDescription__` from appearing as the default description for Icon constants

- app/assets/stylesheets/general/_titles.scss
- app/helpers/content_helper.rb
- app/views/wiki/articles/show.html.erb
Headers rendered with `ContentHelper:markdown` now get an id derived from the content of the header, and a nested link to change the hash of the page to that id, so users can quickly jump to sections of a markdown document.
I checked on the default renderer from Redcarpet. While it does have a similar option, it is only active when using Table of Contents, which we don't always want.
As part of this change, I had add a style rule and used :is() for simplicity. :is() seems to have [good browser support](https://caniuse.com/?search=%3Ais), though I'm not sure which browser we want to support here.
> Add links to markdown-generated headers

- app/assets/stylesheets/editor/_editor-wiki.scss
- app/javascript/src/components/editor/EditorWikiSearch.svelte
While the inline wiki is pretty useful, sometimes you want to open multiple browser tabs and have different wikis open, and the search can help with that.
With this change, search result items now behave like normal `<a>`s, meaning you can middle click to open the article on a new tab, or use the browser's context menu for links.
> Convert search result items on editor wiki search from buttons to links

- app/assets/stylesheets/general/_form.scss
- app/controllers/posts_controller.rb
- app/javascript/src/components/form/Derivatives.svelte
- app/javascript/src/components/form/Tags.svelte
- app/views/posts/validation.js.erb
- config/webpacker.yml
- spec/features/post_derivations_validation_spec.rb
- spec/rails_helper.rb
- spec/support/post_helpers.rb
- spec/support/webpack.rb
This PR creates a better UX for situations where a derivative may be invalid (e.g. when a derivative has the same import code as the post itself). Previously, the post creation would partially succeed, but the invalid record would cause an invisible error, which would potentially fail future attemps to save.
Now, if any part of the post form causes an error, the entire operation will atomically fail, meaning that a partial success save is no longer possible. In addition, a proper error is returned identifying which derivation caused the issue and for what reason.
> feat: Atomically update post and derivatives

- app/controllers/posts_controller.rb
This PR avoids failing the post form submission when the Discord notification doesn't succeed
> fix: Avoid failing post creation/update on non-business-critical errors

- app/javascript/src/components/editor/CodeMirror.svelte
the regex for const spaces matches both spaces and tabs.  There might be a better regex to grab only spaces without catching the tabs, but an easy fix is to just subtract the number of tabs instead.
> Fix for Auto indenting often being wrong #250

- app/assets/stylesheets/logged_in_user/_inscryb-mde.scss
This is a hack on top of a hack to get the Preview button to say "Preview" in the first place.
Instead of simply setting the ::before content of `.fd-eye` to "Edit", I make the ::before invisible and use "Edit" on the ::after content. This is so the button preserves its width, and the other buttons don't shift around.
> Change Preview button to "Edit" when previewing in the markdown editor

- app/javascript/src/apply-custom-css.js
Even if you have a sanitizer in the middle, sanitizers tend to be bypassable.
> Set custom CSS with `.textContent` instead of `.innerHTML`

- .vscode/launch.json
The launch task only opens the browser on localhost:3000. It does not start the webpack nor rails server.
The benefit of this is that the launched profile is persistant and isolated from your browser profiles. So you can install extensions specific to your workflow (e.g. Svelte DevTools, Rails Panel) and they won't clutter your normal browser experience.
---
This is a pattern I've been using recently, but I understand if it a little niche (even more than #260).
It might be worth to also include launch tasks for webpack and rails, but so far I'm okay with running the commands on the terminal and I didn't feel like debugging launch tasks.
> Add simple VSCode Chrome launch task

- app/javascript/src/components/editor/ProjectsDropdown.svelte
- app/javascript/src/components/editor/SearchObjects.svelte
This PR adds a search box to the ProjectsDropdown component. This allows you to filter the dropdown contents by their title. The search component is fairly generic, allowing it to be used for any other array of objects for any key. The results can be retrieved via a two way bind.
> feat: Add search to ProjectsDropdown

- app/controllers/projects_controller.rb
- app/javascript/src/components/editor/Modals/CreateProjectModal.svelte
- app/javascript/src/components/editor/ProjectsDropdown.svelte
- app/javascript/src/components/editor/Save.svelte
- app/javascript/src/utils/editor.js
- app/javascript/src/utils/project.js
Closes #285 
This PR adds the ability to duplicate a project, creating an exact copy of the content, but of course as a completely new project. This is done by simply passing the content along when creating a project. 
But you may be looking at this thinking "Gee, that's a lot of changes just for duplicating", and you'd be right. There was too much going on in the ProjectsDropdown so I decided to split it up.
1. First up, all common fetch functions have been moved to `utils/project.js`. This includes creating, updating, and destroying a project, among more things.
2. Next the Create modal was moved to it's own component with it's own logic, rather than being housed directly in the ProjectsDropdown component. The modal is still a little bit weird in that it also uses logic from non svelte …
> feat: Duplicate Project

- .eslintrc.yml
- app/javascript/src/lib/OWLanguageLinter.js
- app/javascript/src/utils/compiler.js
- app/javascript/src/utils/editor.js
Syntax
```
@if (lefthand operator righthand) {
put this
} @else {
put this instead
}
```
where the `@else` is optional
- `lefthand` and `righthand` are (so far) only compared as raw strings
- Currently supported operators are == and !=
- Runs after mixins, so it compares against Mixin values instead of `Mixin.XYZ`
- In classic `@mixin` fashion, there is no trimming of the content that gets replaced
- but `lefthand` is right-trimmed and `righthand` is left-trimmed, for code convenience
Left a couple TODOs in the code, maybe we can tackle them in the code review.
Also, adjusted eslint rules so `switch` statements get an indent of 1 (the default in eslint is wrong and there is no way to make me change my mind about it)
> Editor: @if directive

- app/javascript/src/utils/compiler.js
Fixes the `TypeError: Cannot read properties of undefined (reading 'map')` when there is an `@if` with an empty condition like so:
```
@if () {}
```
This has to be handled separately because, when parsing the expression, since there are no characters the for loop would just go to the end, returning an empty object.
> Editor: Fix crash when evaluating an empty expression

- .vscode/launch.json
Allows VSCode users to set breakpoints and inspect variables.
Turns out this was pretty easy: I just needed to use the template configuration, and to install gems and an extension.
> Add VSCode launch task for Rails server

- app/javascript/src/microlight.js
Any single word preceeded by a `@` is highlighted.
> Highlight editor directives as keywords

- .gitignore
- app/helpers/application_helper.rb
- app/javascript/packs/application.js
- app/javascript/service-workers/service-worker.js
- app/views/layouts/application.html.erb
- config/webpack/environment.js
- config/webpacker.yml
- package.json
- public/editor-manifest.json
- yarn.lock
- Add webpacker-pwa which takes care of changing webpack to compile the service worker to public/
- Add manifest.json for the Editor page
- Add less-than-barebones service worker with a no-op `fetch` event handler so browsers show the Install button
Ideally we'd want the service worker to serve an offline page, but we can care about that later.
> Allow Editor to be installable as a Progressive Web App

- app/assets/stylesheets/general/_form.scss
- app/controllers/posts_controller.rb
- app/views/posts/form/_image_upload.html.erb
- config/locales/en.yml
- config/locales/ko.yml
- test/controllers/posts_controller_test.rb
This pull request fixes a bug where the carousel video field would not properly extract a YouTube video link's video ID upon first post creation. It also adds improved validation of the carousel video field, along with more user feedback when providing an invalid carousel video ID or URL.
*Title + code section after submitting with an invalid carousel video field*
*Carousel image upload + video field after submitting with an invalid carousel video field*
> fix: properly validate carousel video field

- app/assets/stylesheets/utilities/_colors.scss
- app/controllers/reports_controller.rb
- app/views/admin/reports/index.html.erb
- app/views/admin/reports/show.html.erb
- config/routes.rb
With this PR notifications send to Discord will provide more data with actionable links right from the embed. The notify_discord action is split up in to two different ones, one for posts and one for comments. They could probably have been combined in some smart way, but this felt like the cleaner (and easier) solution.
Posts contain info about the post itself. Namely the title, code, image, if it has a snippet, and the start of a description. All of which are useful when determining if a code is real.
Comments contains the comment body itself. There are no links set up to view the comment in the admin or on the post itself. We rarely (if ever) get comment reports so I decided not to spend time on it for now.
Both have Accept and Reject buttons, which are really just links, but they do …
> feat: Improve data provided by report notifications

- app/javascript/src/components/editor/EditorWiki.svelte
- app/javascript/src/components/icon/ExternalLink.svelte
Useful when you want to see the article in full screen, or need to see parts of the article which couldn't be rendered otherwise (_\*cough\* \*cough\*_ galleries _\*cough\* \*cough\*_).
Open to suggestions about the design. I'm not too happy with it.
`ExternalLink` icon from https://www.svgrepo.com/svg/510970/external-link
> Add link to open wiki article on a new tab in the editor wiki sidebar

- app/assets/stylesheets/editor/_editor.scss
While mobile phones don't have cursors*, users can resize the window to be small enough to see the mobile layout.
*Users can attach peripherals like mice, and the OS will display a pointer on the screen.
> Use vertical resize cursor on Editor drag handle when in the mobile layout

- app/javascript/src/lib/OWLanguageLinter.js
- app/javascript/src/utils/compiler.js
Use `splitArgumentsString` in places where it should or could be used. On this PR:
- when splitting arguments in the linter
- when splitting parameters of a mixin
> Fix a couple of a cases of splitting parameters not being aware of strings or parenthesis

- app/javascript/src/lib/OWLanguageLinter.js
`test` → `~=`
As if anyone was using the test operator anyway lol.
> Use new operator symbol for regex conditional check in Editor linter

- app/assets/stylesheets/editor/_expandable-snippet.scss
- app/javascript/src/components/editor/ExpandableSnippet.svelte
- Use correct CSS classes for the snippets
- Move scrollbar to the expanded snippet, not the whole page
- Not to happy about how I did this. I had to work around the fact modal is a flex parent. Open to suggestions.
- Put highlighted line into view expanding snippet
> Fix some styling issues with the Editor line finder expanded snippet

- spec/javascript/utils/parse.test.js
This PR adds tests for `parse.js` which was previous part of `editor.js`.
The tests cover some basic (and actual) use cases.
> test: Add tests for parse.js

- app/javascript/src/lib/OWLanguageLinter.js
This little bug disabled linting for the entire file. Oops.
> Prevent Editor linter crash when event type is not in the list of known events with arguments

- app/javascript/src/utils/compiler/each.js
- spec/javascript/utils/compiler/each.test.js
1. Allow array literals to have new lines
```haskell
@each (value in [
one,
two,
three
]) {
Each.pair
}
```
1. Fix detection regex overconsuming when there are multiple loops with array literals in the file
1. Add a test for nested loops
> Fix some issues with the parsing of @each in the Editor

- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/components/editor/Shortcuts.svelte
Some programs use Ctrl+Y, others use Ctrl+Shift+Z. I say: why not both?
> Add Ctrl+Shift+Z as a shortcut for redoing the last action in the Editor

- .vscode/extensions.json
- jsconfig.json
- package.json
- yarn.lock
- Add popular Jest extension to the recommended list
- Install @types/jest as a dev dependency
- Add jsconfig.json with target lib ES2022 to silence some warnings
> Improvements to aid IntelliSense (type hints, autocomplete, etc.) in VSCode

- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/components/editor/Compiler.svelte
- app/javascript/src/components/editor/EditorAside.svelte
- app/javascript/src/components/editor/EditorWikiSearch.svelte
- app/javascript/src/components/editor/FindReplaceAll.svelte
- app/javascript/src/components/editor/ItemFinder.svelte
- app/javascript/src/components/editor/LineFinder.svelte
- app/javascript/src/components/editor/Save.svelte
- app/javascript/src/components/form/Tags.svelte
`KeyboardEvent.key` has been a standard for years. There is no reason to use `.keyCode` anymore.
This improves readability and allows for searching for keybinds more easily.
This PR also enhances the use === instead of == (because why wouldn't you use triple equals unless in very specific cases).
> Replace keyCode → key throughout the Editor code

- app/javascript/src/components/editor/ScriptImporter.svelte
This fixes an issue when importing Workshop code generated via OverPy.
I've also simplified the regex for splitting rules a bit.
> Fix the Editor script importer so it is able to find rules with spaces before the name

- jsconfig.json
VSCode complains that there is some large folder we are not taking into account and so IntelliSense will be disabled.
Instead of trying to find that large folder, we can just manually include the range of *.js files where we want IntelliSense to take effect.
> Make jsconfig.json inclusive, not exclusive

- app/javascript/src/stores/editor.js
- app/javascript/src/utils/compiler/variables.js
- app/javascript/src/utils/debounceStore.js
- app/javascript/src/utils/parse.js
- spec/javascript/utils/compiler/variables.test.js
- Ignore variables inside strings
- Detect variables used in Set, Modify, and Chase Variable actions
- Overhaul detection of player variables
- Any variable delimited with a period counts as a player variable
- Detect nested player variables. E.g.:
```
Event Player.pVar1.pVar2;
Global.gVar1.pVar1; // always assumes gVar1 is a Player
```
- Update tests with new features and edge cases
Aside from the unit tests, I have also tested this by importing and then recompiling the following real-world game modes: [JHEM2 v1.3.0](https://workshop.codes/JHEM2), [1DMTZ v4.0.8](https://workshop.codes/1DMTZ), [7S44N v1.1.1](https://workshop.codes/7S44N), and [PZDS2 v1.0.3](https://workshop.codes/PZDS2). All variables matched, except for variables that were given names but went unused.
> Rework variable extraction in the Editor, debounce autocomplete suggestion extraction

- app/assets/stylesheets/editor/_project.scss
- app/controllers/editor_controller.rb
- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/components/editor/Empty.svelte
- app/javascript/src/components/editor/Modals/CreateProjectModal.svelte
- app/javascript/src/components/editor/ProjectsDropdown.svelte
- app/javascript/src/utils/project.js
This PR adjusts the initial empty state of the Editor, which appears when you are logged out, don't have any projects, or by pressing the logo in the top left.
There are multiple purposes behind these changes;
- The empty state still stated the editor was in Alpha. While this isn't false, it's also a bit meaningless at this point.
- Several of the known bugs were outdated
- It wasn't very actionable
Additionally the wiki sidebar is now always visible.
Showing 2 clear actions;
- "Create your first project" will create a demo project.
- "Check out sample project" will take you to my "Fishing in Antarctica", which is a nice enough demonstration of the editor.
This time the "Create your first project" button will create an empty project with the title "My First Project". One click, no need to …
> feat: Adjust editor empty state

- app/javascript/src/utils/compiler/mixins.js
- spec/javascript/utils/compiler/mixins.test.js
Fixes a problem where given
```
@mixin foo(arg, arg2) {
Mixin.arg2
}
```
`@include foo(a, b)` would render "a2" instead of "b"
> When compiling mixins in the Editor, avoid name overlap by replacing arguments with longer names first

- app/javascript/src/utils/parse.js
- spec/javascript/utils/compiler/variables.test.js
Fixes variable-likes inside strings being extracted (test included).
Also, expand range by one character in `findRangesOfStrings()` to account for the closing quote.
> Actuall check all ranges in `matchAllOutsideRanges()`

- config/arrays/wiki/constants.yml
- config/arrays/wiki/values.yml
Fixed errors caused by the game no longer accepting 0 instead of false for **Workshop Setting Toggle**, and the previously misspelled **Orissa** Fusion Driver
> minor value & constants fix

- app/javascript/src/components/editor/Compiler.svelte
- app/javascript/src/components/editor/FindReplaceAll.svelte
- app/javascript/src/components/editor/ItemFinder.svelte
- app/javascript/src/components/editor/LineFinder.svelte
- app/javascript/src/components/editor/Save.svelte
- app/javascript/src/components/form/Tags.svelte
- app/javascript/src/dropdown.js
- app/javascript/src/modal.js
Turns out `.key` returns the text the user would have typed on a text input.
For example, if the user was pressing Shift + S, then `.key` would be `"S"`. If the user wasn't pressing Shift, then `.key` would be `"s"`.
This makes the Compile keybind work again.
> Replace `KeyboardEvent.key` → `KeyboardEvent.code` wherever possible

- config/arrays/wiki/constants.yml
With this, he who shall not be named is no longer in named in the Workshop
> Rename Flashbang Explosion Sound effect to match Overwatch's changes

- app/javascript/src/utils/compiler/variables.js
- spec/javascript/utils/compiler/variables.test.js
- Restrict variable regex to only letters, numbers, or underscore
- Avoid giving default variable names a new index, causing an error on import (details in d31c8e6d1c4e361a76719b2e44ffcea2bcf26c45)
Both changes include tests.
> Fix some issues related to variable extraction and compilation

- app/javascript/src/lib/OWLanguageLinter.js
Fixes diagnostic errors in the following code, because "Mixin.Buttons" would not have been a valid variable iterable
```haskell
@mixin TempAllowAndPressButtons(Player, Buttons) {
@each (button in Mixin.Buttons) {
Allow Button(Mixin.Player, Mixin.Button);
Press Button(Mixin.Player, Mixin.Button);    
Disallow Button(Mixin.Player, Mixin.Button);            
}
}
@include TempAllowAndPressButtons(Event Player, [Button(Primary Fire), Button(Jump)])
```
> Add "Mixin.whatever" as a valid iterable for `findEachLoopsWithInvalidIterables` the Editor linter rule

- app/assets/stylesheets/elements/_alert.scss
- app/javascript/packs/logged-in-user.js
- app/javascript/src/components/Alert.svelte
- app/javascript/src/components/Alerts.svelte
- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/components/form/Dropzone.svelte
- app/javascript/src/lib/alerts.js
- app/javascript/src/utils/projectBackups.js
- app/views/application/_flash.html.erb
- app/views/application/error.js.erb
- app/views/application/success.js.erb
- features/manage_posts.feature
- features/post_access_control.feature
- features/step_definitions/global_stepdefs.rb
- features/wiki_articles.feature
- spec/features/comment_spec.rb
- spec/features/profiles_spec.rb
- spec/system/forgot_passwords_spec.rb
The alerts were a bit of a mishmash, using javascript inside of svelte components. This made enough sense in the main website, but in the editor it's not the best experience.
This PR refactors it to use a svelte component. This component is still used in the main website as well, so it's not just for the editor. To be able to use this from any javascript, instead of setting some store or something, it fires a custom event that is captured by the alerts component. It now uses svelte transitions as well, which is neat.
It still is a bit of a mishmash in the sense that there is also the rails flash, which use the exact same structure and classes, but is just flat HTML. Odd, but that's the way of things.
> refactor: Use svelte component for alerts

- app/javascript/src/components/form/Dropzone.svelte
This PR fixes an issue which prevented the "Browse Files On Device" button from opening a prompt to select images to upload, while also adding metadata which specifies which file types can be selected.
> minor image Dropzone fixes/improvements

- app/javascript/src/utils/compiler/each.js
- spec/javascript/utils/compiler/each.test.js
Fixes an issue where an array iterable spanning multiple lines could confuse the compiler when run with linemarkers inserted.
I'm not very happy with having to account for the linemarkers in the compiler directly, I'd much rather change the line finder and compiler so this metadata isn't mixed with the actual code. But for now this will do.
```
[linemarker]d3ae10|1[/linemarker]@each (pair, i in [
[linemarker]d3ae10|2[/linemarker]	// Name, Value
[linemarker]d3ae10|3[/linemarker]	["True", True]
[linemarker]d3ae10|4[/linemarker]]) {
[linemarker]d3ae10|5[/linemarker]	@each (thing, j in Each.pair) {
[linemarker]d3ae10|6[/linemarker]		Each.thing (Each.i);
[linemarker]d3ae10|7[/linemarker]	}
[linemarker]d3ae10|8[/linemarker]}
[linemarker]d3ae10|9[/linemarker]
```
this would've previously …
> Remove any [linemarkers] in @each array items

- app/javascript/src/components/Bugsnag.svelte
- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/components/editor/Modals/CreateProjectModal.svelte
- app/javascript/src/components/editor/Save.svelte
- app/javascript/src/utils/project.js
- app/views/editor/index.html.erb
- package.json
- yarn.lock
We've had some reports of projects seemingly not saving after coming back to the editor. This PR doesn't fix that necessarily, but it adds a fall back. The project will now also be saved to your local storage, along with a timestamp. When fetching a project your local storage is also fetched. If the timestamp of the local storage project is newer than that of the fetched project, something may have gone wrong previously. In this case we use the content of the local storage project instead.
I thought about adding some alert along the lines of "Your local save is newer than the save on the server, do you want to use this instead?", similar to steam back ups saves perhaps, but it felt like this was too convoluted and most people won't have a clue what that means. So I decided to keep it …
> feat: Use localStorage as fall back for saving projects

- app/javascript/src/utils/compiler/variables.js
- spec/javascript/utils/compiler/variables.test.js
- Avoid detecting variables from numbers without
a whole number part (e.g. ".1234")
- Handle beginning of text in the regex (e.g. don't detect variables when the input is literally "0.abc" or "D.abc")
> Improve editor detection of variables in the context of numbers

- app/assets/stylesheets/elements/_well.scss
- app/assets/stylesheets/utilities/_border_radius.scss
- app/helpers/svelte_helper.rb
- app/javascript/packs/logged-in-user.js
- app/javascript/src/components/form/LimitedCheckboxes.svelte
- app/views/posts/form/tabs/_settings.html.erb
- features/step_definitions/post_stepdefs.rb
- patches/webpacker-svelte+1.0.0.patch
- spec/support/post_helpers.rb
- test/controllers/posts_controller_test.rb
This PR replaces the multi select box for categories with a svelte component. The multi select is unpredictable and annoying to use. By using regular checkboxes we make the whole UX make clear, as you don't need to hold an additional button to select more categories. The checkboxes automatically limit themselves to 3 items, making the validation much simpler as well. Even if you didn't read can you only select 3, you will be forced to. The old validation is still in place in case someone tries to game the system.
> feat: Replace category select

- app/assets/stylesheets/elements/_video.scss
- app/assets/stylesheets/general/_form.scss
- app/assets/stylesheets/logged_in_user/_inscryb-mde.scss
- app/assets/stylesheets/logged_in_user/_switch.scss
- app/helpers/content_helper.rb
- app/javascript/packs/application.js
- app/javascript/src/inscryb-mde.js
- app/javascript/src/inscrybe-mde-insert-video.js
- app/javascript/src/lazy-video.js
This PR adds an optional toggle to autoplay videos. When videos are marked as autoplay they have no controls, are muted, and loop.
To accommodate this all videos will now lazy load, which is done through an intersection observer.
Set set a video as autoplay you can use the toggle in the video uploader or add "autoplay" to the end of the video tag like `[video http://some_url autoplay]`
https://github.com/Mitcheljager/workshop.codes/assets/12848235/d33e724a-b389-4a49-a26b-c902a8ac9c5d
> feat: Autoplay video

- app/javascript/src/utils/compiler/variables.js
- spec/javascript/utils/compiler/variables.test.js
- Fixed an off-by-one bug that saved some variables from being excluded when they shouldn't
- Fixed an issue where variables past Z were being excluded
Also added JSDocs explaining how the logic should work, and improved tests by splitting them up into smaller testable chunks
> Improve Editor variable excluding logic to better match what the game wants

- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/stores/editor.js
With this PR your scroll state will be remembered when navigating between different items. So if you scroll 100 pixels on file A, go to file B, and back to file A, file A will still be scroll 100 pixels.
The event is bound using a codemirror plugin. Unfortunately this event is also fired when the state updates, so when changing between items. This messes with the scroll position, as it would set it to a seemingly random scroll position. To prevent this from happening I added a variable that is toggled when changing between two items. If this variable is true the scroll position isn't saved. This is wrapped in a `setTimeout` with no time set to wait for the next render tick, so as to wait for the view update to complete.
> feat(editor): Remember scroll state between different items

- app/models/user.rb
- app/views/comments/_comment.html.erb
- app/views/filter/get_verified_users.html.erb
- app/views/posts/show.html.erb
- app/views/profiles/_form.html.erb
- app/views/profiles/_image.html.erb
- app/views/profiles/_profile.html.erb
Now that Discord images expire we can no longer store their avatar urls. Battle.net already didn't have avatars, so this PR simply removes provider profile images altogether.
An alternative would be to store the actual from from the moment someone logs in, but that would require us to store that image _every time_ they log in, as we have no way to tell if they changed their image with the provider.
> chore: Remove provider profile image

- app/javascript/src/utils/compiler/mixins.js
- spec/javascript/utils/compiler/mixins.test.js
This PR adds content slots. Content slots allow you to define multiple different `@contents` properties. For example:
```swift
@mixin someSpecialRule() {
rule("Global Rule") {
event {
Ongoing - Global;
}
conditions {
@contents("conditions");
Some Special Condition();
}
actions {
@contents("actions");
Some Special Action();
}
}
}
@include someSpecialRule() {
@slot("conditions") {
Some Slot Condition();
}
@slot("actions") {
Some Slot Action();
}
}
```
Which will result in
```swift
rule("Global Rule") {
event {
Ongoing - Global;
}
conditions {
Some Slot Condition();
Some Special Condition();
}
actions {
Some Slot Action();
Some Special Action();
}
}
```
You can still use the default slot as before, it will take all non slot content and use that as the default.
```swift
@mixin someMixin() { …
```
> feat(editor): Content slots

- config/arrays/wiki/actions.yml
- config/arrays/wiki/constants.yml
- config/arrays/wiki/events.yml
- config/arrays/wiki/values.yml
- lib/tasks/generate_wiki_articles.rake
This PR cleans up the actions/values/events/constants yaml files.
This includes:
- Replace all capital case with title case (eg. HEALTH -> Health)
- Replace all "(un)signed float/int(eger)" with "Float/Integer". Signed is not a thing in the workshop, and it makes no sense for us to list it. It also clears up incosistencies with some being called "int" and others "integer"
- Replace all "bool" with "Boolean"
- Remove all "guid" declarations, they are unused and will remain so
- Remove all languages other than en-US. We aren't maintaining these, so let's keep the data consistent.
This is all preparation for spicing up the arguments section of wiki articles.
> chore: Clean up wiki data

- app/assets/stylesheets/elements/_items.scss
One-liner.
Given
```
1. ul li 1
* ul li 1, ol li 1
* ul li 2, ol li 2
2. ul li 2
3. ul li 3
1. ul li 3, ul li 1
2. ul li 3, ul li 2
4. ul li 4
* ul li 4, ol li 1
```
Before
After
> Only apply ordered list counter style tolist items immediately after an unordered list

- app/assets/stylesheets/elements/_ide.scss
- app/views/posts/_snippet.html.erb
- Move action buttons to the top right, so users don't have to scroll all the way down to toggle fullscreen or copy the snippet to clipboard
- Increase z-index the search bar's filter actions toggle button doesn't render on top of the fullscreen ide view
- Remove rounded corners
> Small improvements to the posts snippet viewer ("ide")

- app/assets/stylesheets/elements/_codemirror.scss
- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/lib/OWLanguageLegacy.js
- app/javascript/src/lib/OWLanguageLinter.js
- app/javascript/src/utils/compiler/compile.js
- app/javascript/src/utils/compiler/parameterObjects.js
- app/javascript/src/utils/parse.js
- spec/javascript/utils/compiler/parameterObjects.test.js
When working with actions or values with many parameters it can be quite a hassle. Either you only end up changing one or two of the values, or you end up with many values that make it difficult to see what is what. To address this this PR adds parameter objects. In terms of javascript you can look at it like a function `someFunction(someValue, someOtherValue)` vs `someFunction({ param1: someValue, param2: someOtherValue })`. The syntax I implemented here is very similar to that.
For example in this action all I'm doing is changing the position:
```js
Create In-World Text(All Players(All Teams), Custom String("Some string"), Vector(9, 9, 9), 1, Clip Against Surfaces, Visible To Position And String, Color(white), Default Visibility);
```
With parameter objects we can write it like this …
> feat(editor): Parameter Objects

- app/javascript/src/utils/compiler/subroutines.js
- spec/javascript/utils/compiler/subroutines.test.js
While there is linter logic to catch these, it is sometimes hard to see the linter error in certain cases.
An argument can be made that, because the in-game editor allows for creating a subroutine but never defining a rule for it, we should also allow it as well.
In fact, this change fixes a case where importing a snippet that declares a subroutine but never define it, then compiling the project and trying to import that into the game would cause a workshop error because we stripped the subroutine from the subroutines list.
Also: refactor `getSubroutines` to use `String.matchAll()`, which is a bit better than `String.match()` and a ton of `String.replace()`s.
> Include subroutines used in actions in the compiled output of the Editor

- app/javascript/src/lib/OWLanguageLinter.js
Makes sure to only detect them outside of strings.
>  Add lint rule to the Editor that warns about usage of triple equals

- app/javascript/src/lib/OWLanguageLegacy.js
Keywords with special accents were not being highlighted as expected. This PR fixes that by including these characters in the regex. It's a bit of a ChatGPT special, but it seems to work well.
Before | After
--- | ---
> fix: Include special characters in syntax highlighting

- app/javascript/src/components/editor/CodeMirror.svelte
* Empty lines containing only a linebreak are no longer removed upon shift-tabbing with several lines of code selected.
* Shift-tabbing after selecting a chunk of code at the start of a line no longer causes the selection to jump to the line above.
* Shift-tabbing after selecting a chunk of code at the very start of a file no longer results in "Uncaught RangeError: Invalid position -1".
* Shift-tabbing with the cursor in front of other code no longer selects the first character following the cursor.
Auto indent on linebreak:
* Pressing Enter while the cursor is located somewhere in the middle of indentation will no longer build more and more indents for each new line.
* Pressing Enter on a line with a open bracket now only indent if the cursor is inside the bracket.
> Fixed several bugs with indentations

- app/javascript/src/utils/compiler/mixins.js
- spec/javascript/utils/compiler/mixins.test.js
I had a mixin that looked like this:
```
@mixin projectileHeroSettings(hero, speed = 50, size = 0.1, radius = 0, timeBetweenShots = 0, maxRange = 0, delay = 0) {
```
The problem was that include result in a whole bunch of `50, 0.1, 0, 0, 0, 0.1` values because I only wanted to change the last value.
This PR changes that by allows parameter objects to be used in mixins, which lucky was a lot easier than expected, however it did present one issue; you might want to use parameter objects as values for your parameters, and how do we know if it's an object for the mixin or to be used literally? We don't. The solution I came up with is that if you provide only one parameters which is an object, we assume it's for the mixin. If you provide multiple we assume it's to be used literally.
That might …
> feat: Allow parameter objects to be used for in mixins

- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/utils/codemirror/indent.js
`CodeMirror.svelte` was becoming too large and hard to process. This PR moves all indent related function to a separate file. Functions are largely unchanged but I had to make some small changes to accommodate the move. I've also included JSDocs for all of the functions. Additionally I've moved some functions in `CodeMirror.svelte` around to make a little more sense.
> refactor: Move indent function to separate file

- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/components/editor/Settings.svelte
- app/javascript/src/stores/editor.js
- app/javascript/src/utils/codemirror/indent.js
This PR adds an options to the settings dropdown to autocomplete using parameter objects. All autocompletes will use parameter objects instead of their regular format. When you change the settings the completions map is regenerated with the new corresponding format.
Along with that settings there's a setting to only do this if the completion has more than x arguments, defaulting to 2. If it has less than the given amount the regular format will be used. This is mostly to prevent silly parameter objects like `Button({ Button: Melee })`.
Since the autocompletions can be multi line I added a function that transforms transactions in CodeMirror that contain new lines to use the expected amount of tabs. An added benefit of this is that this fixes a bug with pasting code that contains tabs that …
> feat: Autocomplete using parameter objects

- app/javascript/src/utils/compiler/parameterObjects.js
- spec/javascript/utils/compiler/parameterObjects.test.js
Fixes an issue where parameter keys would internally contain the [linemarker]s, meaning we wouldn't find the correct argument positions and just use default values instead.
Fixes #402
> Remove [linemarker]s from parameter object keys in the Editor compiler

- app/javascript/src/utils/codemirror/indent.js
Since #410 there is an error when copypasting code on a line that already has code: "Uncaught RangeError: Invalid count value: -2"
Adding Math.max() as a temporary solution, not sure what is causing it?
Adding back a bugfix (prevent auto-indents on enter from adding up infinitely when the cursor is outside of an open bracket) that disappeared with the change to some of the functions
added a selectionDirection constant to prevent the selection from flipping around when tabbing (cursor used to always jump to 'to' position, even when it started at 'from')
> bugfix for indents after #410

- app/javascript/src/utils/codemirror/indent.js
when did the zero fall away and how did i not notice it missing? 🤔
reapplying the 0 so that it actually does something
> missed a 0 in last fix

- app/javascript/src/utils/codemirror/indent.js
Further adjustments to the code for auto-indents! the goal is to allow pasting of whitespace characters, to make copy-pasting on the same line work as it used to (duplicate line), and to keep the structure of indents for code that is either pasted in a marked area or on lines that already have code. the behavior should be fairly close to what is used in vscode.
> Adjustments for auto-indents when pasting code

- app/javascript/src/lib/OWLanguageLinter.js
The argumentsString variable builds up to extreme lengths when argumentClosing is -1 (no closing parenthesis).
Reproduce with code:
```hs
rule("Each Player Rule")
{
event
{
Ongoing - Each Player;
All;
All;
}
conditions
{
}
actions
{
Apply Impulse(Event Player, Dot Product(Velocity Of(
Event Player), Normalize(X Component Of(Throttle))
}
}
```
> Prevent looping when no closing parenthesis is found

- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/components/editor/Settings.svelte
- app/javascript/src/stores/editor.js
- app/javascript/src/utils/codemirror/indent.js
The default values inserted when using autocomplete and parameter objects were not correct. for example, when you expect to get the number 0 you would instead get the string "Number". i changed the code to handle the name and default separately before adding the newlines which did the trick.
Also added semicolons to autocomplete according to issue [#246](https://github.com/Mitcheljager/workshop.codes/issues/246).
The semicolons are inserted only when autocompleting actions. having it insert a semicolon for other type of values could probably get annoying
> Fix default for parameter objects & semicolon after autocomplete

- app/assets/stylesheets/editor/_editor-item.scss
- app/assets/stylesheets/editor/_editor.scss
- app/assets/stylesheets/editor/_matches.scss
- app/assets/stylesheets/elements/_codemirror.scss
- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/components/editor/FindReplaceAll.svelte
- app/javascript/src/utils/codemirror/indent.js
- config/arrays/wiki/actions.yml
- config/arrays/wiki/constants.yml
**pasteIndentAdjustments** Should be pretty friendly. only changes actual tabs and spaces so specialcharacters are not removed, and only adjusts the first line since codemirror does a decent job with the rest. (The previous indent changes were not applied to paste since the code was changed to adjust indents for autocomplete separately).
**searchScrollMargin**
Makes sure the searched results are not hidden behind the search window.
**_matches.scss** and **FindReplaceAll.svelte**:
Make the items that are excluded from compiler show with line-through text in the search.
**_codemirror.scss**:
Show which of the search results are actually selected.
**_editor.scss**:
Make the scrollbar easier to click.
**_editor-item.scss**:
Make it easier to click the beginning of the item name, and prevent …
> Indent on paste and search adjustments

- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/utils/text.js
When Autocomplete using Parameter Objects was enabled the compiler would include the parameter names in the compiled result, resulting in something like:
```
Create HUD Text(
Visible To: All Players(All Teams), Custom String("Test"), 
Subheader: Null, 
Text: Null, 
Location: Left, 
Sort Order: 0, 
Header Color: Color(white), 
Subheader Color: Color(white), 
Text Color: Color(white), 
Reevaluation: Visible To And String, 
Spectators: Default Visibility);
```
This happened because the value set in the completions map for `parameter_default` was set to the same value as `apply`, which is used for autocompletions. As a result it would insert the value as if it was the autocomplete value, including all the keys for the parameter object.
I fixed this by setting the param `parameter_default` …
> fix(editor): Fix incorrect compiled values when using Autocomplete using Parameter Objects

- app/javascript/src/utils/compiler/variables.js
- spec/javascript/utils/compiler/variables.test.js
variables were not being added correctly when using parameter objects, sometimes causing errors when variables end up being added as undefined.
repro: autocomplete For Player Variable or Chase Player Variable At Rate as parameter objects, then try autocompleting anything.
> evaluate parameter objects in getVariables and tests

- app/assets/stylesheets/elements/_dropdown.scss
- app/javascript/src/components/editor/DragHandle.svelte
- app/javascript/src/components/editor/EditorList.svelte
- app/javascript/src/components/editor/Settings.svelte
- app/javascript/src/stores/editor.js
Added a short delay when touching the EditorList for mobile so that you can scroll and click them easier without accidentally moving the items. (fallbackTolerance should also help)
Moved the settings modal a bit to the right for small screens so that it doesnt get cutoff on the left side.
The requestAnimationFrame in DragHandle.svelte make moving the DragHandles less laggy, should work for both PC and mobile.
> Mobile editor and DragHandle tweaks

- app/javascript/src/utils/compiler/variables.js
- spec/javascript/utils/compiler/variables.test.js
A follow up to #424 which should prevent us from adding `undefined` variables to autocomplete.
> Avoid extracting variables from actions in the Editor if the action doesn't have enough arguments

- app/controllers/editor_controller.rb
- app/javascript/src/components/editor/Editor.svelte
- app/views/editor/index.html.erb
- config/routes.rb
The data for the editor was passed directly from the controller. This was convenient, but it is also hard to cache, and has the potential to slow down the initial response by quite a bit.
This PR refactors the data by moving it to json endpoints, allowing the editor to fetch them after the page has loaded. There's 2 endpoints; One for the general editor data (values, actions, etc), and one for the users projects. They are separate so that the browser can cache the data endpoint without having to invalidate it somehow if the user logs into a different account. The projects endpoint is not cached.
This should alleviate some stress from the server and lower the initial response time. In return the user will see the initial loading spinner for a little longer.
> refactor: Fetch editor data via json rather than passing it via the controller

- .vscode/extensions.json
- .vscode/launch.json
- README.md
- Make Rails Server task an "rdbg" task from [VSCode rdbg Ruby Debugger](https://marketplace.visualstudio.com/items?itemName=KoichiSasada.vscode-rdbg)
- Add Webpack Dev Server launch task to launch `./bin/webpack-dev-server`
- Fix Chrome launch task to link source maps correctly
- Add compound task to launch all tasks at once
- Document launch tasks in README
While it probably doesn't make sense to debug the Webpack Dev Server, it is convenient to have a single task to launch everything at the same time.
> Revamp VSCode launch tasks

- app/assets/stylesheets/elements/_codemirror.scss
- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/lib/codeActionProviders/transformParameterObjectsIntoPositionalParameters.js
- app/javascript/src/lib/codeActions.js
- app/javascript/src/utils/codemirror/indent.js
- app/javascript/src/utils/compiler/parameterObjects.js
- spec/javascript/utils/compiler/parameterObjects.test.js
Similar to VSCode's code actions, add a lighbulb icon near the user's cursor that can be clicked to select refactor actions[1] in the code
[1]: In reality, these are not limited to code refactors, but are meant for it anyway
As the name implies, they convert action arguments to be in one form or the other. E.g. `{ Param 1: value1, Param 2: value2 }` → `(value1, value2)`.
Takes into consideration parameter order and "autocomplete-min-parameter-newlines" for multi-line parameter objects
https://github.com/Mitcheljager/workshop.codes/assets/6181929/932eb9ce-b257-4087-8474-66a30eeb4263
Fixes #437
> Add Code Actions, "Transform parameter objects into positional parameters" and vice-versa code action, to the Editor

- .vscode/launch.json
> **Note:**
> Merges into `Mitcheljager/vite` (#446)
Changes `webRoot`, so Chrome can find the original JavaScript files.
> Restore VSCode breakpoint functionality for JS files

- app/javascript/src/chart.js
A large part of the logged in user specific JS is made up of these charts. Most users will not see this as it only shows when looking at analytics. So to reduce the file size of that entry this commit changes the imports to be fetched async when creating the charts.
This reduces logged-in-user.js from 826kb (270kb gzipped) to 369kb (123kb gzipped)
> refactor: Import metric graphics charts async

- app/javascript/src/utils/compiler/each.js
- app/javascript/src/utils/parse.js
- app/javascript/test/utils/compiler/each.test.js
- app/javascript/test/utils/parse.test.js
`@each` would incorrect split on commas inside of quotes. So `["Thing", "Some, thing"]` would be output as `["\"Thing\"", "\"Some,", "thing\""]`
This PR fixes that by checking all the valid commas before parsing the array, and if the given comma is not in the valid commas, skip that iteration.
> fix(editor): Prevent splitting each on commas in strings

- app/javascript/scss/editor/_codemirror-6.scss
- app/javascript/src/components/editor/CodeMirror.svelte
- app/javascript/src/utils/codemirror/indentedLineWrap.js
Word wrapping did not respect indents, making it hard to use in some situations. This PR adds indents to word wrapping by using a modified version of https://github.com/fonsp/Pluto.jl/blob/eb85b0d34b05ee02e61c0316e6f2ea901afe9ab4/frontend/components/CellInput/awesome_line_wrapping.js. That file is meant for React and uses Lodash, which I've replaced.
This plugin also didn't account for the indent markers or for the highlighted line, which had to be indented negatively to make up for the indent of the entire line.
Perhaps there's a world where this could be an additional toggleable option, but I think for now this is what most people would want from word wrapping (it's what VSCode does by default).
Before | After
--- | ---
> feat(editor): Add intends to line wrapping

- app/javascript/scss/elements/_navigation.scss
- On the wiki and mobile nav menu, use a white color scheme
| On the wiki | On the mobile nav menu |
| --- | --- |
| ![on the wiki](https://github.com/Mitcheljager/workshop.codes/assets/6181929/659ab732-5c2f-4fbb-b012-ea0e2df1789a) | ![on the mobile nav menu](https://github.com/Mitcheljager/workshop.codes/assets/6181929/a8220efb-4158-4630-bd93-0bae3efb0d81) |
- Outside of that, simply add a slight white glow that makes the icon pop
> Increase Discord icon visibility in nav bar

- app/javascript/scss/editor/_codemirror-6.scss
- app/javascript/src/components/editor/Editor.svelte
Turns out Chrome and Firefox handle negative indents differently. This fixes the duplicate indents in Chrome, while keeping the indents normal for Firefox.
~~This code assumes there are only two browser engines. Sorry Ladybird :(~~
> fix(editor): increase text-indent multiplier for word-wrapping indent in Chromium browsers

- app/javascript/scss/editor/_logs.scss
- app/javascript/scss/elements/_tabs.scss
- app/javascript/src/components/editor/Editor.svelte
- app/javascript/src/components/editor/Logs.svelte
- app/javascript/src/utils/files.js
This PR adds a new tab to the Wiki sidebar for live Inspector logs. Users can selector their Workshop inspector logs folder. The most recently edited file will be selected and it's text will be processed to show as log entries. This is useful for copying over data between the Workshop and the Editor. Take for example the position of a player, which requires a fair few clicks to copy over normally, where as now you can simply copy paste it. Log entries are created via the regular `Log To Inspector` function and requires no new syntax.
The directory picker uses `showDirectoryPicker` which is unfortunately not supported by all browsers. It is supported by Chrome, which of course is far and away our biggest users base. Unfortunately it does not work in Firefox :(
> feat(editor): Live inspector logs

- app/javascript/src/components/Notifications.svelte
- app/javascript/src/stores/notifications.ts
- app/javascript/src/types/main.d.ts
This refactors the notifications component to use Svelte 5 and TS. With this also come some additional refactors. Previous the dropdown used the dropdown logic of the main site, showing and hiding with regular JS. This commit changes that by wrapping the content is an if statement, only rendering it when needed. This also allows us to add a little transition. Previous the `active` variable was used to animate the bell itself, and nothing but that. That variable is moved to the actual active state and a new variable `animating` is added to set the animating state.
Additionally I've changed the .then chains to more readable `async await`
> refactor(svelte5): Use TS and Svelte 5 syntax for Notifications component

- app/javascript/src/components/form/LimitedCheckboxes.svelte
This component is used in setting (for categories) and in profile blocks (for selecting posts). A pretty straight forward one, no refactoring was done beyond the ts and Svelte upgrade.
> refactor(svelte5): Use ts and Svelte 5 for LimitedCheckboxes

- app/javascript/src/components/Alert.svelte
- app/javascript/src/components/Alerts.svelte
- app/javascript/src/types/global.d.ts
This converts the Alert and Alerts component this TS and Svelte 5. With this I refactored the components a little to be more readable, hopefully anyway.
Similar to https://github.com/Mitcheljager/workshop.codes/pull/506, I added `onalert` on the global object as the event can be fired from anyway on the window object.
> refactor(svelte5): Use ts and Svelte 5 syntax for Alerts

- app/views/pages/privacy_policy.html.erb
- app/views/profiles/_form.html.erb
This PR removes outdated references to Elo Hell in the privacy policy and the verified user blurb
> feat: remove elo hell references in copy

- app/javascript/scss/editor/_codemirror-6.scss
- app/javascript/src/lib/codeActionProviders/transformParameterObjectsIntoPositionalParameters.ts
- Search for the correct completion type when calculating for which completion we should provide this code action
- Adjust z-index of lightbulb button to be +1 the z-index of the CodeMirror gutter
> fix(editor code actions): make transformParameterObjectsIntoPositionalParameters code action appear again

- app/javascript/src/components/editor/Modals/Modals.svelte
- app/javascript/src/components/editor/Modals/TranslationKeysModal.svelte
- app/javascript/src/lib/OWLanguageLinter.ts
- app/javascript/src/types/editor.d.ts
Also:
- Refactor `checkTranslations()` to allow for different diagnostics `from`, `to`, and `severity`
- When opening a modal, pass any properties under `$modal.parameters` as parameters for the modal component
- Used here to open the translation keys modal with the new key already selected
> feature(editor linter): warn about unknown translation keys, allow for creating translation key in-place

- app/javascript/src/components/editor/TranslationKeys/TranslationKeysEditStrings.svelte
- app/javascript/src/lib/OWLanguageLinter.ts
- app/javascript/src/utils/compiler/compile.ts
- app/javascript/src/utils/compiler/translations.ts
- app/javascript/test/utils/compiler/translations.test.js
@netux 
This adds a modifier for the `@translate` feature, allowing you to output a string directly, rather than `Custom String`. This is handy when compiling to a single language and using `@translate` in places it normally wouldn't work. One example of that is the description in settings.
Static keys can not have arguments, as that makes no sense. A linter was added for this.
>  feat(translations): Add static modifier to @translate 

- app/javascript/src/utils/compiler/variables.ts
- app/javascript/test/utils/compiler/variables.test.js
Variables would still be evaluated from comments. This commit fixes that by removing comments before extracting variables.
Before | After
--- | ---
> fix(editor): Remove comments before extracting variables
